version: "3.7"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    hostname: nginx
    restart: always
    ports:
      - 80:80
    privileged: true
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./www:/var/www/localhost
    networks:
      - app_net

  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis:/data
    networks:
      - app_net

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    hostname: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./config/mysql:/etc/mysql/conf.d
      - ./config/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=toYkXrB3ekejI5Rb
    networks:
      - app_net

  memcache:
    image: memcached:alpine
    hostname: memcache
    container_name: memcache
    restart: always
    ports:
      - 11211:11211
    networks:
      - app_net

networks:
  app_net:
    external:
      name: app_net